DROP TABLE IF EXISTS T_BOOK
DROP TABLE IF EXISTS T_USER
DROP TABLE IF EXISTS R_USER_BOOK

CREATE TABLE T_BOOK
(
	BookId	BIGINT IDENTITY(1 , 1) PRIMARY KEY
	, BookName VARCHAR(200) NOT NULL
)


CREATE TABLE T_USER
(
	UserId	BIGINT IDENTITY(1 , 1) PRIMARY KEY
	, UserName VARCHAR(200) NOT NULL
)

CREATE TABLE R_USER_BOOK
(
	BookId	BIGINT NOT NULL
	, UserId BIGINT  NOT NULL
	, BorrowBeginDate DATE NOT NULL
	, BorrowEndDate DATE NULL
)

GO


INSERT INTO T_USER 
Select 'Mathis'

INSERT INTO T_USER 
Select 'Angèle'

INSERT INTO T_USER 
Select 'Ruben'

INSERT INTO T_USER
Select 'David'


INSERT INTO T_BOOK 
Select 'Le seigneur des anneaux'

INSERT INTO T_BOOK 
Select 'Le nom de la rose'

INSERT INTO T_BOOK 
Select 'Tintin au Tibet'